import {cart,saveCart,catalog,money,api,apiBase,auth,unitPrice,maxQuantity,isDigital} from '../lib/commerce';
const el=(id:string)=>document.getElementById(id)!;
const text=(id:string,value:string)=>{el(id).textContent=value;};
let coupon='',quote:any=null,checkoutPayload:any=null,config:any=null,revision=0;
let paypalButtons:any=null;
function invalidate(){revision++;quote=null;checkoutPayload=null;paypalButtons?.close();paypalButtons=null;el('paypal-buttons').replaceChildren();text('shipping','At checkout');text('tax','At checkout');text('discount','—');text('total-label','Item total');const subtotal=cart().reduce((s,l)=>s+unitPrice(l.sku,config?.prices)*l.quantity,0);text('subtotal',money(subtotal));text('total',money(subtotal));}
function render(){invalidate();const lines=cart();el('cart-lines').replaceChildren();el('empty-cart').hidden=!!lines.length;el('shipping-form').hidden=!lines.length||!config?.checkoutEnabled;
const softwareOnly=lines.length>0&&lines.every(l=>isDigital(l.sku));
el('shipping-form').querySelector('h2')!.textContent=softwareOnly?'Billing details':'Delivery details';
el('shipping-form').querySelector('h2 + p')!.textContent=softwareOnly?'US billing address. Your state decides sales tax. Your license key appears on your account page as soon as payment is confirmed.':'US delivery addresses only. Availability is checked before payment.';
 for(const line of lines){const p=catalog.find(x=>x.sku===line.sku)!;const row=document.createElement('article');row.className='cart-line';const img=document.createElement('img');img.src=p.image;img.alt=p.name;const info=document.createElement('div');const h=document.createElement('h2');h.textContent=p.name;const subtitle=document.createElement('p');subtitle.textContent=p.subtitle;const label=document.createElement('label');label.htmlFor='qty-'+p.sku;label.textContent='Quantity';const input=document.createElement('input');input.id=label.htmlFor;input.type='number';input.min='1';input.max=String(maxQuantity(p.sku));input.step='1';input.value=String(line.quantity);input.addEventListener('change',()=>{if(!input.checkValidity()){input.reportValidity();input.value=String(line.quantity);return;}saveCart(cart().map(x=>x.sku===p.sku?{...x,quantity:Number(input.value)}:x));});const remove=document.createElement('button');remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+p.name);remove.addEventListener('click',()=>saveCart(cart().filter(x=>x.sku!==p.sku)));info.append(h,subtitle,label,input,remove);const price=document.createElement('p');price.className='line-price';price.textContent=money(unitPrice(p.sku,config?.prices)*line.quantity);row.append(img,info,price);el('cart-lines').append(row);}
}
document.addEventListener('cart-change',()=>{render();text('coupon-status',coupon?'Code will be rechecked when you review the total.':'');});window.addEventListener('storage',e=>{if(e.key==='borgas-cart-v1')render();});
el('coupon-form').addEventListener('submit',async e=>{e.preventDefault();coupon=(el('coupon') as HTMLInputElement).value.trim().toUpperCase();invalidate();if(!coupon){text('coupon-status','Discount code removed.');return;}const version=revision;try{const result=await api('/discount',{lines:cart(),code:coupon});if(version!==revision)return;text('coupon-status',result.message);text('discount','−'+money(result.discount));const subtotal=cart().reduce((sum,line)=>sum+unitPrice(line.sku,config?.prices)*line.quantity,0);text('total',money(subtotal-result.discount));}catch(e){if(version===revision)text('coupon-status',e instanceof Error?e.message:'Could not check this code.');}});
el('shipping-form').addEventListener('input',()=>invalidate());
el('shipping-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget as HTMLFormElement;invalidate();const version=revision;const button=form.querySelector<HTMLButtonElement>('button')!;button.disabled=true;text('payment-status','Checking your order…');try{if(!auth)throw new Error('Sign-in is not available yet.');const {data}=await auth.auth.getUser();if(!data.user){el('sign-in').hidden=false;throw new Error('Please sign in before checkout.');}el('sign-in').hidden=true;const address=Object.fromEntries(new FormData(form));const payload={lines:cart(),code:coupon,address};const result=await api('/quote',payload);if(version!==revision)return;quote=result;checkoutPayload=payload;text('discount','−'+money(quote.discount));text('shipping',money(quote.shipping));text('tax',money(quote.tax));text('total',money(quote.total));text('total-label','Total');text('payment-status',config.sandbox?'SANDBOX TEST — no real charge. Shipping ($10) and tax ($12) are test amounts.':'Review your total, then continue with PayPal.');await loadPayPal();if(version!==revision)return;
 const paypal=(window as any).paypal;
 paypalButtons=paypal.Buttons({style:{layout:'vertical',label:'paypal'},createOrder:async()=>{if(version!==revision)throw new Error('Your cart changed. Review the total again.');const created=await api('/orders',{...payload,expectedTotal:quote.total});return created.paypalId;},onApprove:async(data:any)=>{text('payment-status','Confirming payment…');try{const result=await api('/capture',{paypalId:data.orderID});if(result.status==='paid'){saveCart([]);el('shipping-form').hidden=true;text('payment-status',(config.sandbox?'Sandbox test payment confirmed. Test order ':'Payment confirmed. Order ')+result.id.slice(0,8).toUpperCase()+'. See your account for order history.');text('checkout-status',config.sandbox?'Sandbox test complete. No hardware will be shipped.':'Thank you for your order.');}else text('payment-status','Payment is pending. Please check your account before trying again.');}catch(error){text('payment-status','Payment confirmation is delayed. Check your account or contact BORGAS before paying again.');}},onCancel:()=>text('payment-status','PayPal checkout was cancelled. Your cart is saved.'),onError:()=>text('payment-status','PayPal could not complete checkout. Check your account before retrying if you approved a payment.')});await paypalButtons.render('#paypal-buttons');}
 catch(error){text('payment-status',error instanceof Error?error.message:'Could not prepare checkout.');}finally{button.disabled=false;}});
el('sandbox-open').addEventListener('click',async()=>{if(!config?.sandbox||!quote||!checkoutPayload){text('payment-status','Enter your delivery details and review the total first.');return;}const button=el('sandbox-open') as HTMLButtonElement;const approvalWindow=window.open('about:blank','borgas-paypal-sandbox');button.disabled=true;text('payment-status','Preparing the PayPal Sandbox approval page…');try{await api('/orders',{...checkoutPayload,expectedTotal:quote.total});const result=await api('/sandbox/approval',{expectedTotal:quote.total});if(result.approval){if(approvalWindow)approvalWindow.location.href=result.approval;else window.location.assign(result.approval);text('payment-status','Approve the Sandbox payment in the new tab, then return here and finish it.');}else{approvalWindow?.close();text('payment-status','This Sandbox payment is already approved. Finish it below.');}}catch(error){approvalWindow?.close();text('payment-status',error instanceof Error?error.message:'Could not open PayPal Sandbox.');}finally{button.disabled=false;}});
el('sandbox-finish').addEventListener('click',async()=>{if(!config?.sandbox||!quote){text('payment-status','Enter your delivery details and review the total first.');return;}const button=el('sandbox-finish') as HTMLButtonElement;button.disabled=true;text('payment-status','Confirming the Sandbox payment…');try{const result=await api('/sandbox/complete',{expectedTotal:quote.total});if(result.status==='paid'){saveCart([]);el('shipping-form').hidden=true;text('payment-status','Sandbox test payment confirmed. Test order '+result.id.slice(0,8).toUpperCase()+'. See your account for order history.');text('checkout-status','Sandbox test complete. No hardware will be shipped.');}else text('payment-status','Payment is pending. Check your account before trying again.');}catch(error){text('payment-status',error instanceof Error?error.message:'Could not confirm the Sandbox payment.');}finally{button.disabled=false;}});
let sdk:Promise<void>|undefined;
function loadPayPal(){if(!sdk)sdk=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://www.paypal.com/sdk/js?client-id='+encodeURIComponent(config.clientId)+'&currency=USD&intent=capture&components=buttons';script.onload=()=>resolve();script.onerror=()=>{sdk=undefined;script.remove();reject(new Error('PayPal could not load. Please try again.'));};document.head.append(script);});return sdk;}
render();
if(apiBase)void api('/config').then(data=>{config=data;render();el('sandbox-fallback').hidden=!config.sandbox;if(config.checkoutEnabled){text('checkout-status',config.sandbox?'SANDBOX TEST ONLY — use a PayPal Sandbox buyer account. No real charges or shipments. Test shipping is $10 and tax is $12.':'Sign in, enter your delivery details and review your total before paying.');if(auth)void auth.auth.getUser().then(({data})=>{el('sign-in').hidden=!!data.user;});else el('sign-in').hidden=false;}else text('checkout-status','Online checkout is being prepared. Your cart is saved.');}).catch(()=>text('checkout-status','Checkout is temporarily unavailable. Your cart is saved; please try again later.'));

document.addEventListener('cart-storage-unavailable',()=>text('payment-status','Browser storage is unavailable. Your cart cannot be saved between pages.'));
