import test from 'node:test';
import assert from 'node:assert/strict';
import worker from './worker.mjs';
const env={DB:{},CHECKOUT_ENABLED:'false',PAYPAL_ENV:'sandbox',SANDBOX_TEST_MODE:'true',SANDBOX_TEST_EMAIL:'tester@example.test',PAYPAL_CLIENT_ID:'test',Paypal_Secret:'test',PAYPAL_MERCHANT_ID:'merchant',PAYPAL_WEBHOOK_ID:'hook',SUPABASE_URL:'https://auth.test',SUPABASE_PUBLISHABLE_KEY:'test',SITE_ORIGIN:'https://borgas.us',SANDBOX_PREVIEW_ORIGIN:'http://127.0.0.1:4322'};
test('Sandbox configuration accepts existing secret spelling and labels test fees',async()=>{const r=await worker.fetch(new Request('https://api.test/config'),env);const c=await r.json();assert.equal(c.checkoutEnabled,true);assert.equal(c.sandbox,true);assert.equal(c.testFees,true);});
test('test flags and preview origin cannot enable live checkout',async()=>{const r=await worker.fetch(new Request('https://api.test/config'),{...env,PAYPAL_ENV:'live'});assert.equal((await r.json()).checkoutEnabled,false);const cors=await worker.fetch(new Request('https://api.test/config',{headers:{Origin:'http://127.0.0.1:4322'}}),{...env,PAYPAL_ENV:'live'});assert.equal(cors.status,403);});
test('missing tester identity disables Sandbox',async()=>{const r=await worker.fetch(new Request('https://api.test/config'),{...env,SANDBOX_TEST_EMAIL:''});assert.equal((await r.json()).checkoutEnabled,false);});
test('Live checkout requires approved policies and production auth email',async()=>{const live={...env,PAYPAL_ENV:'live',SANDBOX_TEST_MODE:'false',CHECKOUT_ENABLED:'true',PAYPAL_SECRET:'secret',FREE_US_SHIPPING:'true',SALES_TAX_STATE:'MA',SALES_TAX_BPS:'625'};let r=await worker.fetch(new Request('https://api.test/config'),live);assert.equal((await r.json()).checkoutEnabled,false);r=await worker.fetch(new Request('https://api.test/config'),{...live,POLICIES_APPROVED:'true',AUTH_EMAIL_READY:'true'});assert.equal((await r.json()).checkoutEnabled,true);});
test('only the verified test email may use fixed test fees',async t=>{const original=globalThis.fetch;let email='other@example.test';globalThis.fetch=async()=>Response.json({id:'user',email,email_confirmed_at:'2026-01-01T00:00:00Z'});t.after(()=>{globalThis.fetch=original;});const request=()=>new Request('https://api.test/quote',{method:'POST',headers:{Authorization:'Bearer test','Content-Type':'application/json'},body:JSON.stringify({lines:[{sku:'brc-02',quantity:1}],address:{fullName:'Sandbox Test',addressLine1:'1 Test Street',city:'Test City',state:'NY',postalCode:'12207'}})});assert.equal((await worker.fetch(request(),env)).status,403);email='tester@example.test';const r=await worker.fetch(request(),env);const q=await r.json();assert.equal(r.status,200);assert.equal(q.total,17199);assert.equal(q.environment,'sandbox');assert.equal(q.testFees,true);});

test('test discount is isolated from live checkout',async()=>{const req=()=>new Request('https://api.test/discount',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lines:[{sku:'brc-02',quantity:1}],code:'SANDBOX10'})});const result=await worker.fetch(req(),env);assert.equal((await result.json()).discount,1500);const liveEnv={...env,PAYPAL_ENV:'live',DB:{prepare(){return {bind(){return {first:async()=>null};}};}}};assert.equal((await worker.fetch(req(),liveEnv)).status,400);});
