import {PublicError,items,discountFor,normalizeAddress,calculate,dollars,validCapture,isDigital,tieredPrice} from './pricing.mjs';
import {makeLicense,licensingReady} from './licenses.mjs';
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
function sandboxMode(env){return env.PAYPAL_ENV==='sandbox'&&env.SANDBOX_TEST_MODE==='true'&&!!env.SANDBOX_TEST_EMAIL;}
function builtInDelivery(env){const rate=Number(env.SALES_TAX_BPS);return env.FREE_US_SHIPPING==='true'&&/^[A-Z]{2}$/.test(env.SALES_TAX_STATE||'')&&/^\d+$/.test(env.SALES_TAX_BPS||'')&&Number.isSafeInteger(rate)&&rate>=0&&rate<=10000;}
function ready(env){const credentials=!!(env.DB&&env.PAYPAL_CLIENT_ID&&(env.PAYPAL_SECRET||env.Paypal_Secret)&&env.PAYPAL_MERCHANT_ID&&env.PAYPAL_WEBHOOK_ID&&env.SUPABASE_URL&&env.SUPABASE_PUBLISHABLE_KEY);const liveOperations=env.PAYPAL_ENV!=='live'||env.POLICIES_APPROVED==='true'&&env.AUTH_EMAIL_READY==='true';const delivery=builtInDelivery(env)||!!env.DELIVERY_QUOTE_URL&&!!env.DELIVERY_QUOTE_TOKEN;return credentials&&liveOperations&&(sandboxMode(env)||(env.CHECKOUT_ENABLED==='true'&&delivery&&['sandbox','live'].includes(env.PAYPAL_ENV)));}
function requireTester(env,owner){if(sandboxMode(env)&&owner.email.toLowerCase()!==env.SANDBOX_TEST_EMAIL.trim().toLowerCase())throw new PublicError('Sandbox checkout is restricted to the test account.',403);}
async function body(request){const raw=await request.text();if(raw.length>16000)throw new PublicError('Request too large.',413);try{return JSON.parse(raw);}catch{throw new PublicError('Invalid request.');}}
async function user(request,env){const header=request.headers.get('Authorization')||'';if(!header.startsWith('Bearer ')||header.length>8192)throw new PublicError('Please sign in to continue.',401);if(!env.SUPABASE_URL||!env.SUPABASE_PUBLISHABLE_KEY)throw new PublicError('Customer sign-in is not connected yet.',503);
 const response=await fetch(env.SUPABASE_URL+'/auth/v1/user',{headers:{Authorization:header,apikey:env.SUPABASE_PUBLISHABLE_KEY},signal:AbortSignal.timeout(10000)});if(!response.ok)throw new PublicError('Your session expired. Please sign in again.',401);const data=await response.json();if(!data.id||!data.email||!data.email_confirmed_at)throw new PublicError('Verify your email to continue.',401);return data;}
async function coupon(env,code){if(!code)return null;if(sandboxMode(env)&&code==='SANDBOX10')return {enabled:1,kind:'percent',value:1000,minimum:0};if(typeof code!=='string'||!/^[A-Z0-9_-]{1,40}$/.test(code))throw new PublicError('Enter a valid discount code.');const row=await env.DB.prepare('SELECT * FROM coupons WHERE code = ?').bind(code).first();if(!row)throw new PublicError('This discount code was not found.');return row;}
// BAC's price follows the launch tier: counted from licenses already issued in this payment environment.
async function prices(env){if(!env.DB)return {};const row=await env.DB.prepare("SELECT COUNT(*) AS n FROM licenses WHERE sku = 'bac' AND payment_env = ?").bind(env.PAYPAL_ENV||'sandbox').first();return {bac:tieredPrice('bac',Number(row?.n??0))};}
async function sendLicenseEmail(env,to,licensee,key){if(!env.RESEND_API_KEY||!env.LICENSE_EMAIL_FROM)return false;
 const text='Hi '+licensee+',\n\nThank you for buying BORGAS Asset Creator.\n\nYour license key (copy the whole line, including BAC1-):\n\n'+key+'\n\nGet started:\n1. Download the installer: https://borgas.us/products/asset-creator/\n2. Open BAC, go to Settings > License, paste the key and click Activate.\n3. Open the Engine page to install the 3D engine.\n\nYour key is also on your account page: https://borgas.us/account/\n\nQuestions? Reply to this email or write to hello@borgas.us.\n\nBORGAS';
 const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+env.RESEND_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({from:env.LICENSE_EMAIL_FROM,to:[to],reply_to:'hello@borgas.us',subject:'Your BORGAS Asset Creator license key',text}),signal:AbortSignal.timeout(15000)});
 return response.ok;}
// Issue the purchase key for every digital line of a paid order. Idempotent: the
// UNIQUE(order_id, sku) row means webhook retries and the capture path cannot
// issue two keys. A failure is logged and retried when the buyer opens their
// account page; it never undoes a completed payment.
async function issueLicenses(env,order){if(order.status!=='paid'&&order.status!=='created'&&order.status!=='pending')return;
 let details;try{details=JSON.parse(order.details);}catch{return;}
 for(const line of details.items||[]){if(!isDigital(line.sku))continue;
  const existing=await env.DB.prepare('SELECT license_key, emailed_at FROM licenses WHERE order_id = ? AND sku = ?').bind(order.id,line.sku).first();
  if(!existing){if(!licensingReady(env)){console.error('License signing is not configured; order',order.id,'is paid but has no key yet.');continue;}
   const licensee=(details.address?.fullName||order.email||'BAC customer').trim();
   const issuedAt=new Date().toISOString();
   const {doc,key}=await makeLicense({licensee,orderId:order.id,licenseId:crypto.randomUUID().replace(/-/g,'').slice(0,16),issuedAt,notes:'borgas.us order'},env);
   await env.DB.prepare('INSERT OR IGNORE INTO licenses (license_id,order_id,sku,payment_env,licensee,email,license_key,issued_at) VALUES (?,?,?,?,?,?,?,?)').bind(doc.licenseId,order.id,line.sku,order.payment_env,licensee,order.email,key,issuedAt).run();}
  const row=await env.DB.prepare('SELECT license_key, licensee, emailed_at FROM licenses WHERE order_id = ? AND sku = ?').bind(order.id,line.sku).first();
  if(row&&!row.emailed_at){try{if(await sendLicenseEmail(env,order.email,row.licensee,row.license_key))await env.DB.prepare('UPDATE licenses SET emailed_at = ? WHERE order_id = ? AND sku = ?').bind(new Date().toISOString(),order.id,line.sku).run();}catch(error){console.error('License email failed for order',order.id,error?.message);}}
 }}
async function quote(env,input){const pr=Array.isArray(input?.lines)&&input.lines.some(l=>isDigital(l?.sku))?await prices(env):{};const lines=items(input.lines,pr);
 if(lines.some(l=>l.digital)&&!licensingReady(env))throw new PublicError('BORGAS Asset Creator licenses cannot be issued right now, so this order was not started. Please try again later.',503);const c=await coupon(env,input.code);const subtotal=lines.reduce((s,l)=>s+l.price*l.quantity,0);const discount=discountFor(subtotal,c);const address=normalizeAddress(input.address);
 if(sandboxMode(env))return {...calculate(input.lines,c,{shipping:lines.every(l=>l.digital)?0:1000,tax:1200},pr),address,code:input.code||'',environment:'sandbox',testFees:true};
 await requireInventory(env,lines);
 if(builtInDelivery(env)){const tax=address.state===env.SALES_TAX_STATE?Math.round((subtotal-discount)*Number(env.SALES_TAX_BPS)/10000):0;return {...calculate(input.lines,c,{shipping:0,tax},pr),address,code:input.code||'',environment:env.PAYPAL_ENV};}
 // An authenticated merchant-controlled adapter must return a confirmed shipping/tax quote.
 // No default zero tax or free shipping. It also checks sale availability and supported destinations.
 if(!env.DELIVERY_QUOTE_URL?.startsWith('https://'))throw new PublicError('Delivery is not configured.',503);
 const response=await fetch(env.DELIVERY_QUOTE_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+env.DELIVERY_QUOTE_TOKEN},body:JSON.stringify({items:lines,address,subtotal,discount,currency:'USD'}),signal:AbortSignal.timeout(15000)});
 if(!response.ok)throw new PublicError('Delivery is unavailable for this order. Please contact BORGAS.',422);const delivery=await response.json();if(delivery.available!==true)throw new PublicError('This order is not currently available for delivery.',422);return {...calculate(input.lines,c,delivery,pr),address,code:input.code||'',environment:env.PAYPAL_ENV};}
async function paypal(env,path,payload,key){const base=env.PAYPAL_ENV==='live'?'https://api-m.paypal.com':'https://api-m.sandbox.paypal.com';const tokenResponse=await fetch(base+'/v1/oauth2/token',{method:'POST',headers:{Authorization:'Basic '+btoa(env.PAYPAL_CLIENT_ID+':'+(env.PAYPAL_SECRET || env.Paypal_Secret)),'Content-Type':'application/x-www-form-urlencoded'},body:'grant_type=client_credentials',signal:AbortSignal.timeout(15000)});if(!tokenResponse.ok)throw new PublicError('Payments are temporarily unavailable.',503);const token=await tokenResponse.json();const response=await fetch(base+path,{method:payload===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token.access_token,'Content-Type':'application/json',...(key?{'PayPal-Request-Id':key}:{})},...(payload===undefined?{}:{body:JSON.stringify(payload)}),signal:AbortSignal.timeout(20000)});if(!response.ok)throw new PublicError('PayPal could not confirm this request. Check your orders before retrying.',502);return response.json();}
async function owned(env,id,owner){if(typeof id!=='string'||!/^[A-Z0-9]{8,32}$/.test(id))throw new PublicError('Invalid order.');const order=await env.DB.prepare('SELECT * FROM orders WHERE paypal_id = ? AND user_id = ?').bind(id,owner).first();if(!order)throw new PublicError('Order not found.',404);return order;}
async function releaseExpired(env){if(sandboxMode(env))return;const now=new Date().toISOString();await env.DB.batch([env.DB.prepare("UPDATE inventory SET reserved = reserved - COALESCE((SELECT SUM(quantity) FROM inventory_reservations WHERE sku = inventory.sku AND status = 'reserved' AND expires_at <= ?),0), updated_at = ? WHERE EXISTS (SELECT 1 FROM inventory_reservations WHERE sku = inventory.sku AND status = 'reserved' AND expires_at <= ?)").bind(now,now,now),env.DB.prepare("UPDATE inventory_reservations SET status = 'released', updated_at = ? WHERE status = 'reserved' AND expires_at <= ?").bind(now,now)]);}
async function requireInventory(env,lines){if(sandboxMode(env))return;await releaseExpired(env);const result=await env.DB.prepare('SELECT sku, on_hand - reserved AS available FROM inventory').bind().all();const available=new Map(result.results.map(row=>[row.sku,row.available]));if(lines.filter(line=>!isDigital(line.sku)).some(line=>(available.get(line.sku)??0)<line.quantity))throw new PublicError('One or more products are not currently available in the requested quantity.',409);}
async function createOrderRecord(env,id,owner,q){const insert=env.DB.prepare('INSERT INTO orders (id,user_id,email,total,details,status,created_at,payment_env) VALUES (?,?,?,?,?,?,?,?)').bind(id,owner.id,owner.email,q.total,JSON.stringify(q),'created',new Date().toISOString(),env.PAYPAL_ENV);if(sandboxMode(env)){await insert.run();return;}await requireInventory(env,q.items);const expiresAt=new Date(Date.now()+30*60*1000).toISOString();const now=new Date().toISOString();const statements=[insert];for(const line of q.items.filter(line=>!isDigital(line.sku)))statements.push(env.DB.prepare('UPDATE inventory SET reserved = reserved + ?, updated_at = ? WHERE sku = ?').bind(line.quantity,now,line.sku),env.DB.prepare("INSERT INTO inventory_reservations (order_id,sku,quantity,status,expires_at,updated_at) VALUES (?,?,?,'reserved',?,?)").bind(id,line.sku,line.quantity,expiresAt,now));try{await env.DB.batch(statements);}catch{await requireInventory(env,q.items);throw new PublicError('Inventory changed while this order was being prepared. Please review your cart again.',409);}}
async function releaseOrder(env,id){if(sandboxMode(env))return;const now=new Date().toISOString();await env.DB.batch([env.DB.prepare("UPDATE inventory SET reserved = reserved - COALESCE((SELECT SUM(quantity) FROM inventory_reservations WHERE order_id = ? AND sku = inventory.sku AND status = 'reserved'),0), updated_at = ? WHERE EXISTS (SELECT 1 FROM inventory_reservations WHERE order_id = ? AND sku = inventory.sku AND status = 'reserved')").bind(id,now,id),env.DB.prepare("UPDATE inventory_reservations SET status = 'released', updated_at = ? WHERE order_id = ? AND status = 'reserved'").bind(now,id)]);}
async function discardOrder(env,id){if(sandboxMode(env)){await env.DB.prepare('DELETE FROM orders WHERE id = ? AND paypal_id IS NULL').bind(id).run();return;}const now=new Date().toISOString();await env.DB.batch([env.DB.prepare("UPDATE inventory SET reserved = reserved - COALESCE((SELECT SUM(quantity) FROM inventory_reservations WHERE order_id = ? AND sku = inventory.sku AND status = 'reserved'),0), updated_at = ? WHERE EXISTS (SELECT 1 FROM inventory_reservations WHERE order_id = ? AND sku = inventory.sku AND status = 'reserved')").bind(id,now,id),env.DB.prepare("UPDATE inventory_reservations SET status = 'released', updated_at = ? WHERE order_id = ? AND status = 'reserved'").bind(now,id),env.DB.prepare('DELETE FROM orders WHERE id = ? AND paypal_id IS NULL').bind(id)]);}
async function reconcile(env,order,paypalOrder){if(validCapture(order,paypalOrder,env.PAYPAL_MERCHANT_ID)){const now=new Date().toISOString();const statements=[env.DB.prepare("UPDATE orders SET status = 'paid', capture_id = ? WHERE id = ? AND status != 'paid'").bind(paypalOrder.purchase_units[0].payments.captures[0].id,order.id)];if(!sandboxMode(env))statements.push(env.DB.prepare("UPDATE inventory SET on_hand = on_hand - COALESCE((SELECT SUM(quantity) FROM inventory_reservations WHERE order_id = ? AND sku = inventory.sku AND status = 'reserved'),0), reserved = reserved - COALESCE((SELECT SUM(quantity) FROM inventory_reservations WHERE order_id = ? AND sku = inventory.sku AND status = 'reserved'),0), updated_at = ? WHERE EXISTS (SELECT 1 FROM inventory_reservations WHERE order_id = ? AND sku = inventory.sku AND status = 'reserved')").bind(order.id,order.id,now,order.id),env.DB.prepare("UPDATE inventory_reservations SET status = 'consumed', updated_at = ? WHERE order_id = ? AND status = 'reserved'").bind(now,order.id));await env.DB.batch(statements);try{await issueLicenses(env,{...order,status:'paid'});}catch(error){console.error('License issue failed for order',order.id,error?.message);}return 'paid';}if(paypalOrder.status==='COMPLETED')throw new PublicError('Payment requires review. Contact BORGAS with your order number.',409);await env.DB.prepare("UPDATE orders SET status = 'pending' WHERE id = ? AND status != 'paid'").bind(order.id).run();return 'pending';}
async function route(request,env){const url=new URL(request.url);const path=url.pathname.replace(/\/$/,'');
 if(path==='/config'&&request.method==='GET')return json({checkoutEnabled:ready(env),clientId:ready(env)?env.PAYPAL_CLIENT_ID:null,prices:await prices(env).catch(()=>({})),licensing:licensingReady(env),...(sandboxMode(env)?{sandbox:true,testFees:true}:{})});
 if(!env.DB)throw new PublicError('The shop service is not configured yet.',503);
 if(path==='/discount'&&request.method==='POST'){const input=await body(request);const subtotal=items(input.lines).reduce((s,l)=>s+l.price*l.quantity,0);const c=await coupon(env,input.code);if(!c)throw new PublicError('Enter a discount code.');return json({discount:discountFor(subtotal,c),message:'Code accepted. Your final discount is checked again before payment.'});}
 if(path==='/orders'&&request.method==='GET'){const owner=await user(request,env);const result=await env.DB.prepare('SELECT id, created_at, total, status, payment_env, fulfillment_status, details, email FROM orders WHERE user_id = ? ORDER BY created_at DESC LIMIT 50').bind(owner.id).all();for(const o of result.results){if(o.status==='paid'){try{await issueLicenses(env,o);}catch(error){console.error('License retry failed for order',o.id,error?.message);}}}const keys=await env.DB.prepare('SELECT l.order_id, l.sku, l.license_key FROM licenses l JOIN orders o ON o.id = l.order_id WHERE o.user_id = ?').bind(owner.id).all();return json({orders:result.results.map(({details,email,...o})=>({...o,licenses:keys.results.filter(k=>k.order_id===o.id).map(k=>({sku:k.sku,key:k.license_key}))}))});}
 if(path==='/webhook'&&request.method==='POST'){if(!env.PAYPAL_WEBHOOK_ID)throw new PublicError('Webhook not configured.',503);const event=await body(request);const verification=await paypal(env,'/v1/notifications/verify-webhook-signature',{auth_algo:request.headers.get('paypal-auth-algo'),cert_url:request.headers.get('paypal-cert-url'),transmission_id:request.headers.get('paypal-transmission-id'),transmission_sig:request.headers.get('paypal-transmission-sig'),transmission_time:request.headers.get('paypal-transmission-time'),webhook_id:env.PAYPAL_WEBHOOK_ID,webhook_event:event});if(verification.verification_status!=='SUCCESS')throw new PublicError('Invalid webhook.',401);
 if(event.event_type==='PAYMENT.CAPTURE.COMPLETED'){const id=event.resource?.supplementary_data?.related_ids?.order_id;const order=await env.DB.prepare('SELECT * FROM orders WHERE paypal_id = ?').bind(id||'').first();if(order)await reconcile(env,order,await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(id)));}return json({received:true});}
 if(!ready(env))throw new PublicError('Checkout is not open yet.',503);
 const owner=await user(request,env);requireTester(env,owner);
 if(path==='/sandbox/check'&&request.method==='GET'&&sandboxMode(env)){const hook=await paypal(env,'/v1/notifications/webhooks/'+encodeURIComponent(env.PAYPAL_WEBHOOK_ID));const valid=hook.url===env.WEBHOOK_URL&&hook.event_types?.some(event=>event.name==='PAYMENT.CAPTURE.COMPLETED'||event.name==='*');if(!valid)throw new PublicError('The Sandbox webhook URL or event needs correcting.',409);return json({paypalCredentials:'verified',webhook:'verified',environment:'sandbox'});}
 if(path==='/sandbox/approval'&&request.method==='POST'&&sandboxMode(env)){const input=await body(request);if(!Number.isSafeInteger(input.expectedTotal)||input.expectedTotal<=0)throw new PublicError('Review your total before opening PayPal.');const order=await env.DB.prepare("SELECT * FROM orders WHERE user_id = ? AND payment_env = 'sandbox' AND total = ? AND status IN ('created','pending') AND paypal_id IS NOT NULL ORDER BY created_at DESC LIMIT 1").bind(owner.id,input.expectedTotal).first();if(!order)throw new PublicError('Start PayPal checkout once, then use the Sandbox approval page.',409);if(Date.now()-Date.parse(order.created_at)>30*60*1000)throw new PublicError('This checkout expired. Review your cart again.',409);const current=await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(order.paypal_id));const approval=current.links?.find(link=>link.rel==='payer-action'||link.rel==='approve')?.href;if(!approval){if(current.status==='APPROVED'||current.status==='COMPLETED')return json({status:current.status.toLowerCase()});throw new PublicError('PayPal did not provide an approval page. Start checkout again.',409);}return json({approval,status:current.status});}
 if(path==='/sandbox/complete'&&request.method==='POST'&&sandboxMode(env)){const input=await body(request);if(!Number.isSafeInteger(input.expectedTotal)||input.expectedTotal<=0)throw new PublicError('Review your total before finishing payment.');const order=await env.DB.prepare("SELECT * FROM orders WHERE user_id = ? AND payment_env = 'sandbox' AND total = ? AND status IN ('created','pending','paid') AND paypal_id IS NOT NULL ORDER BY created_at DESC LIMIT 1").bind(owner.id,input.expectedTotal).first();if(!order)throw new PublicError('No matching Sandbox checkout was found.',404);if(order.status==='paid')return json({id:order.id,status:'paid'});if(Date.now()-Date.parse(order.created_at)>30*60*1000)throw new PublicError('This checkout expired. Review your cart again.',409);let current=await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(order.paypal_id));if(current.status!=='COMPLETED'){if(current.status!=='APPROVED')throw new PublicError('Approve the payment in PayPal first.',409);await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(order.paypal_id)+'/capture',{},order.id+'-c');current=await paypal(env,'/v2/checkout/orders/'+encodeURIComponent(order.paypal_id));}return json({id:order.id,status:await reconcile(env,order,current)});}
 if(path==='/quote'&&request.method==='POST'){const q=await quote(env,await body(request));return json(q);}
 if(path==='/orders'&&request.method==='POST'){const input=await body(request);const q=await quote(env,input);if(input.expectedTotal!==q.total)throw new PublicError('Your total changed. Please review your order again.',409);const id=crypto.randomUUID();await createOrderRecord(env,id,owner,q);
 const amount=v=>({currency_code:'USD',value:dollars(v)});let order;try{order=await paypal(env,'/v2/checkout/orders',{intent:'CAPTURE',purchase_units:[{custom_id:id,invoice_id:id,payee:{merchant_id:env.PAYPAL_MERCHANT_ID},amount:{...amount(q.total),breakdown:{item_total:amount(q.subtotal),discount:amount(q.discount),shipping:amount(q.shipping),tax_total:amount(q.tax)}},items:q.items.map(l=>({name:l.name,sku:l.sku,quantity:String(l.quantity),unit_amount:amount(l.price),category:l.digital?'DIGITAL_GOODS':'PHYSICAL_GOODS'})),...(q.items.every(l=>l.digital)?{}:{shipping:{name:{full_name:q.address.fullName},address:{address_line_1:q.address.addressLine1,...(q.address.addressLine2?{address_line_2:q.address.addressLine2}:{}),admin_area_2:q.address.city,admin_area_1:q.address.state,postal_code:q.address.postalCode,country_code:'US'}}})}],payment_source:{paypal:{experience_context:{shipping_preference:q.items.every(l=>l.digital)?'NO_SHIPPING':'SET_PROVIDED_ADDRESS',user_action:'PAY_NOW'}}}},id);}catch(error){await discardOrder(env,id);throw error;}
 if(!order.id){await discardOrder(env,id);throw new PublicError('Could not create a payment.',502);}await env.DB.prepare('UPDATE orders SET paypal_id = ? WHERE id = ?').bind(order.id,id).run();return json({id,paypalId:order.id},201);}
 if(path==='/capture'&&request.method==='POST'){const input=await body(request);const order=await owned(env,input.paypalId,owner.id);if(order.payment_env!==env.PAYPAL_ENV)throw new PublicError('This order belongs to a different payment environment.',409);if(order.status==='paid')return json({id:order.id,status:'paid'});let current=await paypal(env,'/v2/checkout/orders/'+order.paypal_id);if(current.status!=='COMPLETED'){if(Date.now()-Date.parse(order.created_at)>30*60*1000){await releaseOrder(env,order.id);throw new PublicError('This checkout expired. Review your cart again.',409);}if(current.status!=='APPROVED')throw new PublicError('Approve the payment in PayPal first.',409);await paypal(env,'/v2/checkout/orders/'+order.paypal_id+'/capture',{},order.id+'-c');current=await paypal(env,'/v2/checkout/orders/'+order.paypal_id);}return json({id:order.id,status:await reconcile(env,order,current)});}
 return json({error:'Not found.'},404);
}
export default {async fetch(request,env){const origin=request.headers.get('Origin');const allowed=origin===env.SITE_ORIGIN||(env.PAYPAL_ENV==='sandbox'&&origin===env.SANDBOX_PREVIEW_ORIGIN);const webhook=new URL(request.url).pathname==='/webhook';if(origin&&!allowed&&!webhook)return json({error:'Origin not allowed.'},403);let response;try{if(request.method==='OPTIONS')response=new Response(null,{status:204});else response=await route(request,env);}catch(error){if(!(error instanceof PublicError))console.error('Commerce request failed:',error?.name,error?.message);response=json({error:error instanceof PublicError?error.message:'The shop is temporarily unavailable. Please try again later.'},error instanceof PublicError?error.status:503);}if(allowed){response.headers.set('Access-Control-Allow-Origin',origin);response.headers.set('Access-Control-Allow-Headers','Authorization, Content-Type');response.headers.set('Access-Control-Allow-Methods','GET, POST, OPTIONS');response.headers.set('Vary','Origin');}response.headers.set('X-Content-Type-Options','nosniff');return response;}};
